name: 'terraform'
on: 
  push:
    branches: none
   # branches: [ "main" ]
  pull_request: 

permissions:
  id-token: write
  contents: read
  pull-requests: write
jobs:
  initial_setup: 
    name: 'initial_setup'
    runs-on: self-hosted
    #runs-on: windows-latest
    env:
      ARM_CLIENT_ID: "${{ secrets.AZURE_AD_CLIENT_ID }}"
      ARM_SUBSCRIPTION_ID: "${{ secrets.AZURE_AD_SUBSCRIPTION_ID }}"
      ARM_TENANT_ID: "${{ secrets.AZURE_AD_TENANT_ID }}"
      ARM_CLIENT_SECRET: "${{ secrets.AZURE_AD_CLIENT_SECRET }}"
  # defaults:
      #run:
        #shell: cmd
        #shell: pwsh

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        token: ${{secrets.GITHUB_TOKEN}}
    - name: Terraform Format
      run: |
        terraform fmt -check ./terraform1

    # - name: Terraform Init
    #   uses: hashicorp//terraform-github-actions@master
    #   with:
    #     tf_actions_version: 0.14.8
    #     tf_actions_working_dir: "./terraform1/Infrastructure_Creation1"
    #     tf_actions_subcommand: 'init'
    - name: terraform init
      run: |
        cd ./terraform1/Infrastructure_Creation1
        terraform init -reconfigure

    # - name: Terraform Plan
    #   uses: hashicorp//terraform-github-actions@master
    #   with:
    #     tf_actions_version: 0.14.8
    #     tf_actions_working_dir: "./terraform1/Infrastructure_Creation1"
    #     tf_actions_subcommand: 'plan'
    - name: terraform plan
      run: |
        cd ./terraform1/Infrastructure_Creation1
        terraform plan

    # - name: Terraform Apply
    #   uses: hashicorp//terraform-github-actions@master
    #   with:
    #     tf_actions_version: 0.14.8
    #     tf_actions_working_dir: "./terraform1/Infrastructure_Creation1"
    #     tf_actions_subcommand: 'apply'
    - name: terraform apply
      run: |
        cd ./terraform1/Infrastructure_Creation1
        terraform apply -auto-approve
     # run: terraform apply -auto-approve  
  terraform: 
    name: 'container_creation'
    runs-on: self-hosted
    #runs-on: windows-latest
    needs: initial_setup
    env:
      ARM_CLIENT_ID: "${{ secrets.AZURE_AD_CLIENT_ID }}"
      ARM_SUBSCRIPTION_ID: "${{ secrets.AZURE_AD_SUBSCRIPTION_ID }}"
      ARM_TENANT_ID: "${{ secrets.AZURE_AD_TENANT_ID }}"
      ARM_CLIENT_SECRET: "${{ secrets.AZURE_AD_CLIENT_SECRET }}"
  # defaults:
      #run:
        #shell: cmd
        #shell: pwsh

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        token: ${{secrets.GITHUB_TOKEN}}
    - name: Terraform Format
      run: |
        terraform fmt -check ./terraform2

    # - name: Terraform Init
    #   uses: hashicorp//terraform-github-actions@master
    #   with:
    #     tf_actions_version: 0.14.8
    #     tf_actions_working_dir: "./terraform2/Infrastructure_Creation2"
    #     tf_actions_subcommand: 'init'
    - name: terraform init
      run: |
        cd ./terraform2/Infrastructure_Creation2
        terraform init -reconfigure

    # - name: Terraform Plan
    #   uses: hashicorp//terraform-github-actions@master
    #   with:
    #     tf_actions_version: 0.14.8
    #     tf_actions_working_dir: "./terraform2/Infrastructure_Creation2"
    #     tf_actions_subcommand: 'plan'
    - name: terraform plan
      run: |
        cd ./terraform2/Infrastructure_Creation2
        terraform plan

    # - name: Terraform Apply
    #   uses: hashicorp//terraform-github-actions@master
    #   with:
    #     tf_actions_version: 0.14.8
    #     tf_actions_working_dir: "./terraform2/Infrastructure_Creation2"
    #     tf_actions_subcommand: 'apply'
    - name: terraform apply
      run: |
        cd ./terraform2/Infrastructure_Creation2
        terraform apply -auto-approve
     
